/* Illustrative data for the CURRENT prototype. Every person, credential, statistic and
   piece of feedback below is fictional. `photo` fields name the file each slot expects in images/.

   ONE PROFILE SCHEMA renders every sailor (profile.html?p=<slug>). A sailor can crew, helm,
   skipper or teach; there is no separate "crew" or "skipper" profile. Fields fall into three groups:

   1. USER-PROVIDED   what Create profile collects: name, photos, sailingArea, bio, sailingSince,
                      types, roles, boats, credentials
   2. VERIFICATION    a separate check, never typed in: verification.identity
   3. COMMUNITY       generated by confirmed CURRENT sails, never typed in: confirmedSails,
                      repeatConnections, feedback, recent and (via TOGETHER below) sailedWith */

window.CURRENT_DATA = {};

const VERIFIED = { identity: true };

const PEOPLE = [
  /* ---- Maya Ellison ---- */
  {
    slug: "maya-ellison", name: "Maya Ellison", verification: VERIFIED,
    photo: "images/skipper-maya-ellison.jpg", heroPhoto: "images/profile-maya-ellison.jpg",
    sailingArea: "San Francisco Bay Area", sailingSince: 2016,
    bio: "Bay Area sailor focused on keelboat racing, with experience across bow, trim and pit.",
    types: ["Racing", "Day sailing", "Keelboats"],
    roles: [
      { name: "Bow", note: "Spinnaker sets and douses, and calling the distance to the mark." },
      { name: "Trimmer", note: "Jib and spinnaker. Comfortable in a breeze." },
      { name: "Pit", note: "Halyards and line management." },
      { name: "Helm", note: "Skippers a J/105 out of Sausalito on Saturday mornings." },
    ],
    boats: [
      { name: "J/105", sails: 14 }, { name: "Express 27", sails: 11 },
      { name: "Melges 24", sails: 9 }, { name: "Catalina 34", sails: 7 },
    ],
    credentials: [
      { issuer: "US Sailing", name: "Basic Keelboat", number: "458732", year: 2019 },
      { issuer: "US Sailing", name: "Small Boat Level 1 Instructor", number: "512094", year: 2022 },
    ],
    confirmedSails: 41, repeatConnections: 9,
    feedback: [
      { from: "tom-reyes", sail: "Friday Night Race", boat: "Express 27", quote: "Great on trim and communicated clearly throughout the race." },
      { from: "ana-ferreira", sail: "Practice Sail", boat: "Melges 24", quote: "Positive attitude, great crew member and really helped keep the boat running smoothly." },
    ],
    recent: [
      { date: "SEP 18", title: "Friday Night Race", boat: "Express 27", place: "Berkeley Marina", role: "Jib trim" },
      { date: "SEP 12", title: "Casual Bay Sail", boat: "Catalina 34", place: "Sausalito", role: "Crew" },
      { date: "SEP 09", title: "Practice Sail", boat: "Melges 24", place: "Alameda", role: "Trimmer" },
      { date: "AUG 30", title: "Sunday Race", boat: "J/105", place: "South Beach Harbor", role: "Bow" },
    ],
  },
  /* ---- Tom Reyes ---- */
  {
    slug: "tom-reyes", name: "Tom Reyes", verification: VERIFIED,
    photo: "images/skipper-tom-reyes.jpg", heroPhoto: "images/profile-tom-reyes.jpg",
    sailingArea: "Berkeley Marina · San Francisco Bay", sailingSince: 2011,
    bio: "Runs a friendly Friday night boat out of Berkeley where new crew get a real job, not just a place to sit.",
    types: ["Racing", "Day sailing", "Keelboats"],
    roles: [
      { name: "Helm", note: "Steers on the racecourse and in the harbor." },
      { name: "Tactician", note: "Calls the shifts and the starts when someone else drives." },
    ],
    boats: [{ name: "Express 27", sails: 42 }, { name: "J/105", sails: 11 }, { name: "Santa Cruz 27", sails: 10 }],
    credentials: [
      { issuer: "US Sailing", name: "Basic Keelboat", number: "371205", year: 2013 },
      { issuer: "Sample training provider", name: "Adult First Aid and CPR", number: "FA-20417", year: 2024 },
    ],
    confirmedSails: 63, repeatConnections: 12,
    feedback: [
      { from: "maya-ellison", sail: "Friday Night Race", boat: "Express 27", quote: "Puts new crew at ease and runs a tidy, well-briefed boat." },
      { from: "jules-moreau", sail: "Friday Night Race", boat: "Express 27", quote: "Clear calls on the start line, and always debriefs at the dock." },
    ],
    recent: [
      { date: "SEP 18", title: "Friday Night Race", boat: "Express 27", place: "Berkeley Marina", role: "Skipper" },
      { date: "SEP 11", title: "Friday Night Race", boat: "Express 27", place: "Berkeley Marina", role: "Skipper" },
      { date: "SEP 04", title: "Friday Night Race", boat: "Express 27", place: "Berkeley Marina", role: "Skipper" },
      { date: "AUG 23", title: "Sunday Sail", boat: "Express 27", place: "Berkeley Marina", role: "Skipper" },
    ],
  },
  /* ---- Ana Ferreira ---- */
  {
    slug: "ana-ferreira", name: "Ana Ferreira", verification: VERIFIED,
    photo: "images/skipper-ana-ferreira.jpg", heroPhoto: "images/profile-ana-ferreira.jpg",
    sailingArea: "Alameda · San Francisco Bay", sailingSince: 2009,
    bio: "Melges 24 owner and one-design regular. Practices most Wednesdays, races on Sundays, and likes crew who ask questions.",
    types: ["Racing", "Coaching", "Dinghies"],
    roles: [
      { name: "Helm", note: "Steers her own Melges 24." },
      { name: "Tactician", note: "Occasionally calls tactics on friends' boats." },
      { name: "Instructor", note: "Runs Wednesday practice sails on starts and boat handling." },
    ],
    boats: [{ name: "Melges 24", sails: 61 }, { name: "J/105", sails: 17 }, { name: "Laser", sails: 10 }],
    credentials: [
      { issuer: "US Sailing", name: "Small Boat Level 2 Instructor", number: "204718", year: 2018 },
      { issuer: "US Sailing", name: "Basic Keelboat", number: "188456", year: 2012 },
    ],
    confirmedSails: 88, repeatConnections: 14,
    feedback: [
      { from: "dev-patel", sail: "Sunday Race", boat: "Melges 24", quote: "Calm under pressure and precise on the starts. Wanted to sail again straight away." },
      { from: "maya-ellison", sail: "Practice Sail", boat: "Melges 24", quote: "A patient coach. Explained every start sequence, then let us try it ourselves." },
    ],
    recent: [
      { date: "SEP 20", title: "Sunday Race", boat: "Melges 24", place: "St. Francis Yacht Club", role: "Skipper" },
      { date: "SEP 16", title: "Practice Sail", boat: "Melges 24", place: "Alameda", role: "Instructor" },
      { date: "SEP 09", title: "Practice Sail", boat: "Melges 24", place: "Alameda", role: "Instructor" },
      { date: "AUG 30", title: "Sunday Race", boat: "Melges 24", place: "St. Francis Yacht Club", role: "Skipper" },
    ],
  },
  /* ---- Chris Park ---- */
  {
    slug: "chris-park", name: "Chris Park", verification: VERIFIED,
    photo: "images/skipper-chris-park.jpg", heroPhoto: "images/profile-chris-park.jpg",
    sailingArea: "South Beach Harbor · San Francisco Bay", sailingSince: 2005,
    bio: "Delivers boats along the California coast. Patient, organized about weather and watches, and good at making a long passage feel short.",
    types: ["Deliveries", "Offshore", "Cruising"],
    roles: [
      { name: "Skipper", note: "In command on every delivery, with a written watch schedule." },
      { name: "Navigator", note: "Weather routing and passage planning." },
    ],
    boats: [{ name: "Beneteau 40", sails: 19 }, { name: "Jeanneau 379", sails: 19 }, { name: "Catalina 42", sails: 14 }],
    credentials: [
      { issuer: "US Sailing", name: "Offshore Safety at Sea", number: "630112", year: 2021 },
      { issuer: "US Sailing", name: "Basic Cruising", number: "245903", year: 2012 },
    ],
    confirmedSails: 52, repeatConnections: 8,
    feedback: [
      { from: "jules-moreau", sail: "Monterey to San Francisco Delivery", boat: "Beneteau 40", quote: "Well-organized watches and calm through the night. A great passage." },
      { from: "ingrid-larsen", sail: "Half Moon Bay Overnight", boat: "Jeanneau 379", quote: "Careful with the weather and made sure everyone got rest." },
    ],
    recent: [
      { date: "SEP 06", title: "Monterey to San Francisco Delivery", boat: "Beneteau 40", place: "Monterey", role: "Skipper" },
      { date: "AUG 08", title: "Half Moon Bay Overnight", boat: "Jeanneau 379", place: "San Francisco", role: "Skipper" },
      { date: "JUN 14", title: "SF to Santa Barbara Delivery", boat: "Catalina 42", place: "San Francisco", role: "Skipper" },
    ],
  },
  /* ---- Dev Patel ---- */
  {
    slug: "dev-patel", name: "Dev Patel", verification: VERIFIED,
    photo: "images/sailor-dev-patel.jpg", heroPhoto: "images/profile-dev-patel.jpg",
    sailingArea: "Berkeley · San Francisco Bay", sailingSince: 2012,
    bio: "Helms and trims J/105s out of Berkeley. Likes a well-run boat and a proper debrief afterwards.",
    types: ["Racing", "Keelboats"],
    roles: [
      { name: "Helm", note: "Steers J/105s in the Sunday series." },
      { name: "Trimmer", note: "Main and jib on friends' boats." },
    ],
    boats: [{ name: "J/105", sails: 28 }, { name: "Melges 24", sails: 12 }, { name: "Express 27", sails: 7 }],
    credentials: [{ issuer: "US Sailing", name: "Basic Keelboat", number: "402561", year: 2014 }],
    confirmedSails: 47, repeatConnections: 7,
    feedback: [
      { from: "ana-ferreira", sail: "Sunday Race", boat: "Melges 24", quote: "Sharp on the main and easy to sail with. Always on time." },
      { from: "tom-reyes", sail: "Friday Night Race", boat: "Express 27", quote: "Steady hands in a breeze. Would gladly have him aboard again." },
    ],
    recent: [
      { date: "SEP 20", title: "Sunday Race", boat: "J/105", place: "South Beach Harbor", role: "Helm" },
      { date: "SEP 13", title: "Sunday Race", boat: "J/105", place: "South Beach Harbor", role: "Helm" },
      { date: "SEP 04", title: "Friday Night Race", boat: "Express 27", place: "Berkeley Marina", role: "Trimmer" },
    ],
  },
  /* ---- Ingrid Larsen ---- */
  {
    slug: "ingrid-larsen", name: "Ingrid Larsen", verification: VERIFIED,
    photo: "images/sailor-ingrid-larsen.jpg", heroPhoto: "images/profile-ingrid-larsen.jpg",
    sailingArea: "Sausalito · San Francisco Bay", sailingSince: 2010,
    bio: "Cruising skipper running relaxed daysails from Sausalito to Angel Island. New crew always welcome.",
    types: ["Day sailing", "Cruising"],
    roles: [
      { name: "Helm", note: "Skippers a Catalina 34 on weekends." },
      { name: "Navigator", note: "Chartwork and tides for Bay passages." },
    ],
    boats: [{ name: "Catalina 34", sails: 18 }, { name: "Hunter 33", sails: 11 }],
    credentials: [{ issuer: "US Sailing", name: "Basic Cruising", number: "319847", year: 2015 }],
    confirmedSails: 29, repeatConnections: 6,
    feedback: [
      { from: "maya-ellison", sail: "Casual Bay Sail", boat: "Catalina 34", quote: "A relaxed skipper who made a first-timer on board feel welcome." },
      { from: "chris-park", sail: "Half Moon Bay Overnight", boat: "Jeanneau 379", quote: "Reliable on watch and quick to spot a change in the weather." },
    ],
    recent: [
      { date: "SEP 12", title: "Casual Bay Sail", boat: "Catalina 34", place: "Sausalito", role: "Skipper" },
      { date: "AUG 29", title: "Angel Island Daysail", boat: "Catalina 34", place: "Sausalito", role: "Skipper" },
      { date: "AUG 08", title: "Half Moon Bay Overnight", boat: "Jeanneau 379", place: "San Francisco", role: "Navigator" },
    ],
  },
  /* ---- Jules Moreau ---- */
  {
    slug: "jules-moreau", name: "Jules Moreau", verification: VERIFIED,
    photo: "images/sailor-jules-moreau.jpg", heroPhoto: "images/profile-jules-moreau.jpg",
    sailingArea: "Alameda · San Francisco Bay", sailingSince: 2017,
    bio: "Bow and pit on Express 27s and Melges 24s. Quick on the foredeck and good company on the dock.",
    types: ["Racing", "Keelboats"],
    roles: [
      { name: "Bow", note: "Spinnaker sets, douses and headsail changes." },
      { name: "Pit", note: "Halyards and line management." },
    ],
    boats: [{ name: "Express 27", sails: 16 }, { name: "Melges 24", sails: 12 }, { name: "J/105", sails: 5 }],
    credentials: [{ issuer: "US Sailing", name: "Basic Keelboat", number: "477390", year: 2018 }],
    confirmedSails: 33, repeatConnections: 8,
    feedback: [
      { from: "tom-reyes", sail: "Friday Night Race", boat: "Express 27", quote: "Fast on the bow, and spinnaker sets went smoothly every time." },
      { from: "chris-park", sail: "Monterey to San Francisco Delivery", boat: "Beneteau 40", quote: "Took every watch seriously and kept the mood good. Easy company offshore." },
    ],
    recent: [
      { date: "SEP 18", title: "Friday Night Race", boat: "Express 27", place: "Berkeley Marina", role: "Bow" },
      { date: "SEP 06", title: "Monterey to San Francisco Delivery", boat: "Beneteau 40", place: "Monterey", role: "Crew" },
      { date: "AUG 30", title: "Sunday Race", boat: "Melges 24", place: "St. Francis Yacht Club", role: "Pit" },
    ],
  },
  /* ---- Juhi Desai: the prototype's own "you", the sailor signed in on this browser ----
     No stock photo is used for this one profile — it stands in for whoever is trying the
     prototype, and putting someone else's face under that name would be worse than initials.
     Her confirmedSails/recent/sailedWith below are her starting history; the crew-request
     loop (loop.js) adds to them as you request, get accepted and confirm a sail. */
  {
    slug: "juhi-desai", name: "Juhi Desai", verification: VERIFIED,
    photo: "images/skipper-juhi-desai.jpg", heroPhoto: "images/profile-juhi-desai.jpg",
    sailingArea: "San Francisco Bay Area", sailingSince: 2023,
    bio: "Newer to keelboat racing, building sea time as a trimmer and learning to helm.",
    types: ["Racing", "Keelboats"],
    roles: [
      { name: "Trimmer", note: "Jib on Friday nights. Comfortable up to 15 knots." },
      { name: "Helm", note: "Learning starts and mark roundings on a friend's J/105." },
    ],
    boats: [{ name: "Express 27", sails: 9 }, { name: "J/105", sails: 5 }],
    credentials: [{ issuer: "US Sailing", name: "Basic Keelboat", number: "601233", year: 2023 }],
    confirmedSails: 14, repeatConnections: 3,
    feedback: [
      { from: "tom-reyes", sail: "Friday Night Race", boat: "Express 27", quote: "Solid on the jib and easy to brief. Always ready before the start." },
    ],
    recent: [
      { date: "AUG 21", title: "Friday Night Race", boat: "Express 27", place: "Berkeley Marina", role: "Trimmer" },
      { date: "JUL 24", title: "Friday Night Race", boat: "Express 27", place: "Berkeley Marina", role: "Trimmer" },
    ],
  },
];

/* COMMUNITY HISTORY: how many confirmed sails each pair has shared. Symmetric, so a count
   shown on one profile always matches the other. Sailed-with lists are derived from this. */
const TOGETHER = {
  "maya-ellison|tom-reyes": 6, "ana-ferreira|maya-ellison": 4, "dev-patel|maya-ellison": 3,
  "ingrid-larsen|maya-ellison": 2, "jules-moreau|maya-ellison": 2,
  "ana-ferreira|tom-reyes": 2, "dev-patel|tom-reyes": 4, "ingrid-larsen|tom-reyes": 3, "jules-moreau|tom-reyes": 5,
  "ana-ferreira|dev-patel": 5, "ana-ferreira|jules-moreau": 3, "ana-ferreira|ingrid-larsen": 2,
  "chris-park|jules-moreau": 4, "chris-park|ingrid-larsen": 3, "chris-park|dev-patel": 2,
  "dev-patel|jules-moreau": 3, "ingrid-larsen|jules-moreau": 2, "dev-patel|ingrid-larsen": 2,
  "juhi-desai|tom-reyes": 2,
};
const together = (a, b) => TOGETHER[[a, b].sort().join("|")] || 0;

window.CURRENT_DATA.profiles = Object.fromEntries(PEOPLE.map((p) => [p.slug, p]));

/* Derive sailedWith (top five by shared sails) and the "+N more" from repeatConnections. */
PEOPLE.forEach((p) => {
  const all = PEOPLE.filter((o) => o.slug !== p.slug)
    .map((o) => ({ slug: o.slug, sails: together(p.slug, o.slug) }))
    .filter((o) => o.sails > 0)
    .sort((a, b) => b.sails - a.sails || a.slug.localeCompare(b.slug));
  p.sailedWith = all.slice(0, 5);
  p.sailedWithMore = Math.max(0, p.repeatConnections - p.sailedWith.length);
});
window.CURRENT_DATA.together = together;

/* Find a sail. Each sail belongs to a skipper in `profiles`.
   weekday: 0 = Sunday … 6 = Saturday. daysAfter pushes a sail into a later week.
   `area` drives the location filter and `map` places its pin on the illustrative map. */
window.CURRENT_DATA.sails = [
  {
    id: "friday-night-race", type: "Racing", title: "Friday Night Race",
    boat: "Express 27", location: "Berkeley Marina", area: "Berkeley",
    weekday: 5, time: "17:30", duration: "About 3.5 hours",
    level: "Intermediate+", minLevel: 1, crewNeeded: "1–2 crew", positions: ["Trimmer", "Pit"],
    skipper: "tom-reyes", map: { x: 262, y: 158 },
    about: "The weekly Friday evening series. We race in a mixed fleet and finish at the dock. Looking for someone comfortable trimming the jib in 15 knots or more, and a pit person who keeps lines tidy.",
    meet: "Berkeley Marina, guest dock", bring: "non-marking shoes, warm layer, water",
    photo: "images/sail-friday-night-race-j24.jpg", alt: "A J/24 keelboat racing downwind under a blue spinnaker on San Francisco Bay, crew in the cockpit",
    pos: "50% 60%", posDetail: "50% 68%", ph: "#4c6b80",
    preview: { photo: "images/preview-friday-night-race-fleet.jpg", alt: "A fleet of keelboats racing upwind off Alcatraz on San Francisco Bay", pos: "60% 50%", ph: "#3f6d8e" },
  },
  {
    id: "saturday-morning-sail", type: "Day sail", title: "Saturday Morning Sail",
    boat: "J/105", location: "Sausalito", area: "Sausalito",
    weekday: 6, time: "09:30", duration: "About 4 hours",
    level: "All levels", minLevel: 0, crewNeeded: "2–3 crew", positions: ["Bow", "Trimmer"],
    skipper: "maya-ellison", map: { x: 132, y: 170 },
    about: "An easy morning on the Bay with a stop for coffee off Angel Island. New crew are welcome. I will walk you through the jobs before we leave the dock.",
    meet: "Sausalito, visitor dock", bring: "layers, sunscreen, soft-soled shoes",
    photo: "images/sail-saturday-morning-sail.jpg", alt: "A sailboat under way on blue water in San Francisco Bay", pos: "60% 55%", ph: "#3f7fae",
    preview: { photo: "images/preview-saturday-morning-sail-bay.jpg", alt: "A sailboat on the Bay in afternoon light with the Bay Bridge behind", pos: "40% 55%", ph: "#5b86ad" },
  },
  {
    id: "sunday-race", type: "Racing", title: "Sunday Race",
    boat: "Melges 24", location: "St. Francis Yacht Club", area: "San Francisco",
    weekday: 0, time: "11:00", duration: "About 4 hours",
    level: "Intermediate+", minLevel: 1, crewNeeded: "1–2 crew", positions: ["Pit", "Trimmer"],
    skipper: "ana-ferreira", map: { x: 110, y: 244 },
    about: "Fleet racing on the city front. We practise starts on Wednesdays, so Sunday is a good place to grow. Weight and experience both matter on a Melges 24, so tell me what you have sailed.",
    meet: "St. Francis Yacht Club, guest dock", bring: "foul-weather layer, gloves, non-marking shoes",
    photo: "images/sail-sunday-race-crew.jpg", alt: "Two boats racing close together off Alcatraz", pos: "50% 50%", ph: "#1d3a57",
    preview: { photo: "images/preview-sunday-race-melges-24.jpg", alt: "A Melges 24 crew hiking out under a green spinnaker", pos: "60% 60%", ph: "#4c6b80" },
  },
  {
    id: "monterey-delivery", type: "Delivery", title: "SF to Monterey Delivery",
    boat: "Beneteau 40", location: "San Francisco → Monterey", area: "San Francisco",
    weekday: 5, daysAfter: 7, time: "07:00", multiDay: true, duration: "Two to three days, weather permitting",
    level: "Intermediate+", minLevel: 1, crewNeeded: "2 crew", positions: ["Multiple positions"],
    skipper: "chris-park", map: { x: 184, y: 298 },
    about: "Moving a Beneteau 40 down the coast with an overnight leg. Watches are planned in advance and everyone stands them. You should be comfortable sleeping and working in a seaway.",
    meet: "South Beach Harbor, San Francisco", bring: "foul-weather gear, harness and tether (or borrow one), seasickness plan",
    photo: "images/sail-monterey-delivery.jpg", alt: "A sailboat on open water at sunset", pos: "60% 55%", ph: "#5a2f2f",
  },
];

/* The sailor the prototype treats as "you" when requesting to crew. */
window.CURRENT_DATA.currentUser = "juhi-desai";
