/* Illustrative data for the CURRENT prototype.
   `photo` is the file each opportunity expects in images/ (see README). */

window.CURRENT_DATA = {
  people: {
    "tom-reyes": { name: "Tom R.", verified: true },
    "ingrid-solberg": { name: "Ingrid S.", verified: false },
    "ana-ferreira": { name: "Ana F.", verified: true },
    "dev-mehta": { name: "Dev M.", verified: true },
  },

  opportunities: [
    {
      id: "friday-night-race",
      title: "Friday Night Race",
      boat: "Express 27",
      location: "Berkeley Marina",
      day: "Friday", time: "5:30 PM",
      needs: "Jib / Trim",
      level: "Intermediate+",
      skipper: "tom-reyes",
      photo: "images/sail-friday-night-race.jpg",
      alt: "Express 37 keelboats racing upwind on San Francisco Bay",
      pos: "30% 50%",
      ph: "#2a4a66",
    },
    {
      id: "casual-bay-sail",
      title: "Casual Bay Sail",
      boat: "Catalina 34",
      location: "Sausalito",
      day: "Saturday", time: "10:00 AM",
      needs: "General crew",
      level: "Beginner friendly",
      skipper: "ingrid-solberg",
      photo: "images/sail-casual-bay-sail.jpg",
      alt: "A foiling catamaran sailing past Alcatraz on San Francisco Bay",
      pos: "45% 50%",
      ph: "#6f8ea0",
    },
    {
      id: "practice-sail",
      title: "Practice Sail",
      boat: "Melges 24",
      location: "Alameda",
      day: "Wednesday", time: "6:00 PM",
      needs: "Trimmer / Mainsheet",
      level: "Intermediate",
      skipper: "ana-ferreira",
      photo: "images/sail-practice-sail.jpg",
      alt: "A SailGP catamaran with its wing sail up on San Francisco Bay",
      pos: "50% 78%",
      ph: "#4c6b80",
    },
    {
      id: "sunday-race-crew",
      title: "Sunday Race Crew",
      boat: "J/105",
      location: "South Beach Harbor",
      day: "Sunday", time: "10:30 AM",
      needs: "Bow / Pit",
      level: "Experienced",
      skipper: "dev-mehta",
      photo: "images/sail-sunday-race-crew.jpg",
      alt: "Two SailGP catamarans racing close together off Alcatraz",
      pos: "50% 50%",
      ph: "#1d3a57",
    },
  ],

  profile: {
    slug: "maya-ellison",
    name: "Maya Ellison",
    location: "San Francisco Bay Area",
    photo: "images/profile-maya-ellison.jpg",
    bio: "Started in dinghies, now racing keelboats on the Bay most weekends. Happiest on the bow.",
    tags: ["Racing", "Dinghy", "Keelboat"],
    credentials: ["US Sailing Basic Keelboat"],
    boats: ["J/105", "Express 27", "Melges 24"],
    positions: ["Trimmer", "Bow", "Pit"],
    confirmedSails: 41,
    repeatConnections: 9,
    sailedWith: ["TR", "AF", "DM", "IS", "JK"],
    sailedWithMore: 4,
  },
};
