/* CURRENT — the sailing profile. One template renders every sailor from data.js
   (profile.html?p=<slug>). A sailor can crew, helm, skipper or teach; there is no
   separate crew or skipper layout.

   Three kinds of information are kept visibly apart:
     Verified          identity: checked by a separate process, never typed in
     Provided          entered by the sailor: bio, roles, boats, credentials
     Community-backed  generated by confirmed CURRENT sails: counts, sailed with, feedback, recent sailing */
(() => {
  const root = document.querySelector("[data-profile-page]");
  if (!root) return;

  const data = window.CURRENT_DATA;
  const { esc, verifiedTick, avatar } = window.CURRENT_UI;

  /* A real Supabase-backed profile, shaped exactly like data.js's sample sailors so
     the rest of this template needs no separate code path. Community-history
     fields stay empty here on purpose — those only exist once the crew-request
     loop is rebuilt on real accounts, and identity.verified stays false because
     the database itself has no real verification to say otherwise yet. */
  const fetchRealProfile = async (slug) => {
    const supa = window.CURRENT_SUPABASE;
    if (!supa) return null;
    const { data: row, error } = await supa
      .from("profiles")
      .select(`
        user_id, slug, name, photo_url, home_sailing_area, bio, sailing_since, identity_verified,
        profile_sailing_types ( type ),
        profile_roles ( role, note ),
        profile_boats ( name, experience ),
        profile_credentials ( issuer, name, year, detail )
      `)
      .eq("slug", slug)
      .maybeSingle();
    if (error || !row) return null;
    return {
      slug: row.slug,
      userId: row.user_id,
      name: row.name,
      photo: row.photo_url || "",
      heroPhoto: row.photo_url || "",
      sailingArea: row.home_sailing_area || "",
      bio: row.bio || "",
      sailingSince: row.sailing_since || "",
      types: row.profile_sailing_types.map((t) => t.type),
      roles: row.profile_roles.map((r) => ({ name: r.role, note: r.note || "" })),
      boats: row.profile_boats.map((b) => ({ name: b.name, experience: b.experience })),
      credentials: row.profile_credentials.map((c) => ({ issuer: c.issuer, name: c.name, year: c.year, detail: c.detail || "" })),
      verification: { identity: !!row.identity_verified },
      confirmedSails: 0, repeatConnections: 0,
      sailedWith: [], sailedWithMore: 0, feedback: [], recent: [],
    };
  };

  (async () => {
    const slug = new URLSearchParams(location.search).get("p") || data.currentUser;

    let p = await fetchRealProfile(slug);
    let isMine = false;

    if (p) {
      const session = window.CURRENT_AUTH ? await window.CURRENT_AUTH.getSession() : null;
      isMine = !!session && session.user.id === p.userId;
    } else {
      p = data.profiles[slug];
      /* Your own profile is the one the crew-request loop (loop.js) can change:
         confirming a sail adds to your confirmed sails, recent sailing and sailed-with. */
      if (p && p.slug === data.currentUser && window.CURRENT_LOOP) p = window.CURRENT_LOOP.overlayMe(p);
      isMine = !!p && p.slug === data.currentUser;
    }

    if (!p) {
      root.innerHTML = `
        <div class="container"><div class="page-intro">
          <p class="eyebrow">Sailing profile</p>
          <h1 class="display-2">We could not find that profile.</h1>
          <a class="link-arrow" href="find-a-sail.html">Find a sail <span>→</span></a>
        </div></div>`;
      return;
    }

  const first = p.name.split(" ")[0];
  const person = (s) => data.profiles[s];
  const profileHref = (s) => `profile.html?p=${esc(s)}`;
  const src = {
    verified: `<span class="src src--verified">${verifiedTick("Verified")}Verified</span>`,
    provided: `<span class="src">Provided by ${esc(first)}</span>`,
    community: `<span class="src src--community">Community-backed</span>`,
  };
  const head = (title, tag) => `<div class="pf-head"><h2>${esc(title)}</h2>${tag}</div>`;
  const times = (n) => (n === 1 ? "once" : `${n} times`);
  const hasHistory = p.sailedWith.length > 0 || p.feedback.length > 0 || p.recent.length > 0;

  document.title = `${p.name} — Sailing profile — CURRENT`;

  root.innerHTML = `
    <!-- WHO IS THIS, AND WHAT KIND OF SAILOR? -->
    <section class="pf-intro" aria-labelledby="pf-name">
      <div class="container pf-intro__grid">
        <figure class="pf-photo">
          <div class="photo__frame" style="--ph:#b9c7cf;--pos:50% 35%">
            <div class="photo__media">
              <span class="pf-ini" aria-hidden="true">${esc(p.name.split(" ").map((w) => w[0]).join(""))}</span>
              ${p.heroPhoto ? `<img src="${esc(p.heroPhoto)}" alt="${esc(p.name)} sailing" decoding="async" onerror="this.hidden=true">` : ""}
            </div>
          </div>
        </figure>

        <div class="pf-id">
          <h1 class="pf-name" id="pf-name">${esc(p.name)}${p.verification.identity ? verifiedTick("Identity verified") : ""}</h1>
          <p class="pf-area">${esc(p.sailingArea)}</p>
          <p class="pf-types">${p.types.map(esc).join(" · ")}</p>
          <p class="pf-bio">${esc(p.bio)}</p>

          <dl class="pf-facts">
            <div><dt>Sailing since</dt><dd>${p.sailingSince}</dd></div>
            <div><dt>Roles</dt><dd>${p.roles.map((r) => esc(r.name)).join(" · ")}</dd></div>
            <div class="num"><dd>${p.confirmedSails}</dd><dt>confirmed sails</dt></div>
            <div class="num"><dd>${p.repeatConnections}</dd><dt>repeat connections</dt></div>
          </dl>

          <div class="pf-actions">
            <button class="btn btn--ghost" type="button" data-share>Share profile</button>
            ${isMine ? `<a class="btn btn--ghost" href="create-profile.html">Edit profile</a>` : ""}
          </div>
        </div>
      </div>
    </section>

    <dialog class="modal" aria-labelledby="share-title">
      <div class="modal__panel">
        <p class="label">Share profile</p>
        <h2 class="modal__title" id="share-title">Share ${esc(p.name.split(" ")[0])}’s profile</h2>
        <p class="modal__lede">Send this link anywhere sailors look for crew — a text, a club board, a crew list.</p>
        <p class="share-url">current.sailing/${esc(p.slug)}</p>
        <div class="modal__actions">
          <button class="btn btn--ghost" type="button" data-share-close>Close</button>
          <button class="btn" type="button" data-share-copy>Copy profile link</button>
        </div>
        <p class="small" role="status" aria-live="polite" data-share-status></p>
      </div>
    </dialog>

    <!-- WHAT KIND OF SAILOR? CAN I TRUST THE CONTEXT? -->
    <section class="pf-section" aria-label="Experience and credentials">
      <div class="container pf-two">
        <div class="pf-col">
          ${head("Experience", src.provided)}
          <h3 class="pf-sub">Boats sailed</h3>
          <ul class="pf-list">
            ${p.boats.map((b) => `<li><span>${esc(b.name)}</span><span class="pf-muted">${b.sails != null ? `${b.sails} sails` : esc(b.experience)}</span></li>`).join("")}
          </ul>
          <h3 class="pf-sub">Roles</h3>
          <ul class="pf-list pf-roles">
            ${p.roles.map((r) => `<li><strong>${esc(r.name)}</strong><span class="pf-muted">${esc(r.note)}</span></li>`).join("")}
          </ul>
        </div>

        <div class="pf-col pf-col--rule">
          ${head("Credentials", "")}
          <div class="pf-identity">
            ${p.verification.identity ? verifiedTick("Identity verified") : `<span class="verified verified--off" aria-hidden="true"></span>`}
            <div>
              <p class="pf-identity__title${p.verification.identity ? "" : " pf-identity__title--off"}">${p.verification.identity ? "Identity verified" : "Not verified yet"}</p>
              <p class="pf-muted pf-identity__note">Concept: a third-party identity check, such as ID.me. CURRENT does not store ID documents.</p>
            </div>
            ${p.verification.identity ? src.verified : ""}
          </div>
          <div class="pf-creds">
            ${p.credentials.map((c) => `
              <div class="pf-cred">
                <div>
                  <p class="pf-cred__issuer">${esc(c.issuer)}</p>
                  <p>${esc(c.name)}</p>
                  <p class="pf-muted">${c.number ? `Credential no. ${esc(c.number)} · ` : c.detail ? `${esc(c.detail)} · ` : ""}${c.year}</p>
                </div>
                <span class="src">Provided by ${esc(first)}</span>
              </div>`).join("")}
          </div>
        </div>
      </div>
    </section>

    ${hasHistory ? `
    <!-- WHO HAVE THEY ACTUALLY SAILED WITH? -->
    <section class="pf-section" aria-labelledby="pf-with">
      <div class="container">
        <div class="pf-head">
          <div>
            <h2 id="pf-with">Sailed with</h2>
            <p class="pf-muted pf-head__sub">People ${esc(first)} has sailed with on confirmed sails.</p>
          </div>
          ${src.community}
        </div>
        <ul class="pf-mates">
          ${p.sailedWith.map((w) => {
            const o = person(w.slug);
            return `<li><a class="pf-mate" href="${profileHref(o.slug)}">${avatar(o, "avatar--pf")}<span class="pf-mate__name">${esc(o.name)}</span><span class="pf-muted">${w.sails} sails</span></a></li>`;
          }).join("")}
          ${p.sailedWithMore ? `<li><span class="pf-mate pf-mate--more"><span class="pf-more">+${p.sailedWithMore}</span><span class="pf-mate__name">and ${p.sailedWithMore} more</span></span></li>` : ""}
        </ul>
      </div>
    </section>

    <!-- WHAT WAS IT LIKE TO SAIL WITH THEM? -->
    <section class="pf-section" aria-labelledby="pf-fb">
      <div class="container">
        <div class="pf-head"><h2 id="pf-fb">Sailing feedback</h2>${src.community}</div>
        <div class="pf-feedback">
          ${p.feedback.map((f) => {
            const o = person(f.from);
            const n = data.together(p.slug, o.slug) + (isMine && window.CURRENT_LOOP ? window.CURRENT_LOOP.extraTogether(o.slug) : 0);
            return `
              <article class="fb">
                ${avatar(o, "avatar--fb")}
                <div>
                  <p class="fb__who"><a href="${profileHref(o.slug)}">${esc(o.name)}</a></p>
                  <p class="fb__ctx">${esc(f.sail)} · ${esc(f.boat)}</p>
                  <p class="fb__quote">“${esc(f.quote)}”</p>
                  <p class="fb__foot">
                    <span>Sailed together ${times(n)}</span>
                    <span class="fb__again">${verifiedTick("Would sail together again")}Would sail together again</span>
                  </p>
                </div>
              </article>`;
          }).join("")}
        </div>
      </div>
    </section>

    <!-- WHAT HAVE THEY DONE RECENTLY? -->
    <section class="pf-section pf-section--last" aria-labelledby="pf-recent">
      <div class="container">
        <div class="pf-head"><h2 id="pf-recent">Recent sailing</h2>${src.community}</div>
        <ul class="pf-recent">
          ${p.recent.slice(0, 4).map((r) => `
            <li>
              <span class="pf-recent__date">${esc(r.date)}</span>
              <strong>${esc(r.title)}</strong>
              <span class="pf-recent__meta"><span>${esc(r.boat)}</span><span>${esc(r.place)}</span><span class="pf-muted">${esc(r.role)}</span></span>
            </li>`).join("")}
        </ul>
      </div>
    </section>` : `
    <!-- A brand-new profile has no CURRENT-generated history yet: no fake activity. -->
    <section class="pf-section pf-section--last" aria-labelledby="pf-recent">
      <div class="container">
        <div class="pf-head"><h2 id="pf-recent">Sailing history</h2>${src.community}</div>
        <div class="pf-empty">
          ${isMine
            ? `<p>Your CURRENT history starts when you sail with people through CURRENT.</p>
               <p class="pf-muted">After a sail, both sailors can confirm that you sailed together.</p>`
            : `<p>${esc(first)}’s CURRENT history starts when ${esc(first)} sails with people through CURRENT.</p>
               <p class="pf-muted">After a sail, both sailors can confirm that they sailed together.</p>`}
        </div>
      </div>
    </section>`}`;

  /* Share profile: a conceptual public link, since the prototype has no real hosting for it. */
  const shareModal = root.querySelector(".modal");
  const shareStatus = shareModal.querySelector("[data-share-status]");
  root.querySelector("[data-share]").addEventListener("click", () => {
    shareStatus.textContent = "";
    shareModal.showModal();
  });
  shareModal.querySelector("[data-share-close]").addEventListener("click", () => shareModal.close());
  shareModal.addEventListener("click", (e) => { if (e.target === shareModal) shareModal.close(); });
  shareModal.querySelector("[data-share-copy]").addEventListener("click", async () => {
    const url = shareModal.querySelector(".share-url").textContent;
    try { await navigator.clipboard.writeText(url); } catch (e) { /* prototype link only; show the copied state regardless */ }
    shareStatus.textContent = "Profile link copied ✓";
  });
  })();
})();
