/* CURRENT — the sailing profile. One template renders every sailor from data.js
   (profile.html?p=<slug>). A sailor can crew, helm, skipper or teach; there is no
   separate crew or skipper layout.

   Three kinds of information are kept visibly apart:
     Verified          identity: checked by a separate process, never typed in
     Provided          entered by the sailor: bio, roles, boats, credentials
     Community-backed  generated by confirmed CURRENT sails: counts, sailed with, feedback, recent sailing */
(() => {
  const root = document.querySelector("[data-profile-page]");
  if (!root) return;

  const data = window.CURRENT_DATA;
  const { esc, verifiedTick, avatar } = window.CURRENT_UI;

  /* A real Supabase-backed profile, shaped exactly like data.js's sample sailors so
     the rest of this template needs no separate code path. Community-history
     fields stay empty here on purpose — those only exist once the crew-request
     loop is rebuilt on real accounts, and identity.verified stays false because
     the database itself has no real verification to say otherwise yet. */
  const fetchRealProfile = async (slug) => {
    const supa = window.CURRENT_SUPABASE;
    if (!supa) return null;
    const { data: row, error } = await supa
      .from("profiles")
      .select(`
        user_id, slug, name, photo_url, home_sailing_area, bio, sailing_since, identity_verified,
        profile_sailing_types ( type ),
        profile_roles ( role, note ),
        profile_boats ( name, experience ),
        profile_credentials ( issuer, name, year, detail )
      `)
      .eq("slug", slug)
      .maybeSingle();
    if (error || !row) return null;
    return {
      slug: row.slug,
      userId: row.user_id,
      name: row.name,
      photo: row.photo_url || "",
      heroPhoto: row.photo_url || "",
      sailingArea: row.home_sailing_area || "",
      bio: row.bio || "",
      sailingSince: row.sailing_since || "",
      types: row.profile_sailing_types.map((t) => t.type),
      roles: row.profile_roles.map((r) => ({ name: r.role, note: r.note || "" })),
      boats: row.profile_boats.map((b) => ({ name: b.name, experience: b.experience })),
      credentials: row.profile_credentials.map((c) => ({ issuer: c.issuer, name: c.name, year: c.year, detail: c.detail || "" })),
      verification: { identity: !!row.identity_verified },
      confirmedSails: 0, repeatConnections: 0,
      sailedWith: [], sailedWithMore: 0, feedback: [], recent: [],
    };
  };

  /* Profile dashboard (real, signed-in owner only) --------------------------
     Every real crew request this user has made, sail details embedded via
     the FK. Note: there is currently no policy letting a requester read a
     sail once the skipper closes it (an earlier attempt at one caused RLS
     recursion with sail_requests and was removed) — so this embed can come
     back null for a requested/declined row against a since-closed sail. An
     accepted row is unaffected once confirmed, since sail_participations
     keeps its own permanent snapshot independent of `sails` entirely. */
  const fetchMyRequests = async (userId) => {
    const supa = window.CURRENT_SUPABASE;
    if (!supa) return [];
    try {
      const { data, error } = await supa
        .from("sail_requests")
        .select("id, status, created_at, sails ( id, title, sail_date, start_time, location, status )")
        .eq("requester_user_id", userId)
        .order("created_at", { ascending: false });
      if (error || !data) return [];
      return data.filter((r) => r.sails); // no resolvable sail — skip rather than show a broken row
    } catch (e) {
      return [];
    }
  };

  /* Every real sail this user skippers, with a cheap crew-request count via
     the same embed (just counting ids — no separate aggregate query). */
  const fetchMySails = async (userId) => {
    const supa = window.CURRENT_SUPABASE;
    if (!supa) return [];
    try {
      const { data, error } = await supa
        .from("sails")
        .select("id, title, sail_date, location, status, sail_requests ( id )")
        .eq("skipper_user_id", userId)
        .order("sail_date", { ascending: false });
      return error || !data ? [] : data;
    } catch (e) {
      return [];
    }
  };

  const REQUEST_STATUS_LABEL = { requested: "Requested", accepted: "Accepted", declined: "Declined" };
  const fmtShortDate = (dateStr) => new Date(`${dateStr}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric" });
  const fmtRecentDate = (dateStr) => fmtShortDate(dateStr).toUpperCase();

  /* Permanent sailing history (Phase 4) — public for any real profile, not
     just its owner: sail_participations' "confirmed rows are public" policy
     is what makes this safe to run for anyone viewing anyone's real profile.
     Calculated at read time from real confirmed rows — never a stored
     counter, so it can never drift out of sync with what's actually true.
     "Would sail again" is deliberately not fetched here — it's private and
     never shown on a profile, this phase or otherwise. */
  const fetchConfirmedHistory = async (userId) => {
    const empty = { confirmedSails: 0, repeatConnections: 0, sailedWith: [], sailedWithMore: 0, recent: [], otherProfilesBySlug: {} };
    const supa = window.CURRENT_SUPABASE;
    if (!supa) return empty;
    try {
      const { data: rows, error } = await supa
        .from("sail_participations")
        .select("skipper_user_id, crew_user_id, sail_title, sail_boat, sail_location, sail_date")
        .eq("skipper_confirmed", true)
        .eq("crew_confirmed", true)
        .or(`skipper_user_id.eq.${userId},crew_user_id.eq.${userId}`)
        .order("sail_date", { ascending: false });
      if (error || !rows || !rows.length) return empty;

      const otherIdOf = (r) => (r.skipper_user_id === userId ? r.crew_user_id : r.skipper_user_id);
      const otherIds = [...new Set(rows.map(otherIdOf))];

      const { data: otherProfiles } = await supa
        .from("profiles")
        .select("user_id, slug, name, photo_url")
        .in("user_id", otherIds);
      const slugById = {};
      const otherProfilesBySlug = {};
      (otherProfiles || []).forEach((pr) => {
        slugById[pr.user_id] = pr.slug;
        otherProfilesBySlug[pr.slug] = { slug: pr.slug, name: pr.name, photo: pr.photo_url || "" };
      });

      const sailsByOther = new Map();
      rows.forEach((r) => {
        const slug = slugById[otherIdOf(r)];
        if (slug) sailsByOther.set(slug, (sailsByOther.get(slug) || 0) + 1);
      });
      const sailedWith = [...sailsByOther.entries()]
        .map(([slug, count]) => ({ slug, sails: count }))
        .sort((a, b) => b.sails - a.sails);
      const repeatConnections = sailedWith.filter((w) => w.sails > 1).length;

      const recent = rows.slice(0, 4).map((r) => ({
        date: fmtRecentDate(r.sail_date),
        title: r.sail_title,
        boat: r.sail_boat,
        place: r.sail_location,
        other: slugById[otherIdOf(r)] || "",
      }));

      return { confirmedSails: rows.length, repeatConnections, sailedWith, sailedWithMore: 0, recent, otherProfilesBySlug };
    } catch (e) {
      return empty;
    }
  };

  /* This signed-in user's participation for each of their OWN accepted
     requests, keyed by sail_id — used only to upgrade the "My requests" row
     status below (Accepted → Confirm sail → Waiting → Confirmed sail ✓). */
  const fetchMyParticipationsBySail = async (userId) => {
    const supa = window.CURRENT_SUPABASE;
    if (!supa) return new Map();
    try {
      const { data, error } = await supa
        .from("sail_participations")
        .select("id, sail_id, skipper_confirmed, crew_confirmed")
        .eq("crew_user_id", userId);
      if (error || !data) return new Map();
      return new Map(data.map((p) => [p.sail_id, p]));
    } catch (e) {
      return new Map();
    }
  };

  /* "Accepted" / "Confirm sail" (link) / "Waiting for confirmation" /
     "Confirmed sail ✓" for one My-requests row. The sail-happened check here
     is the same client-side approximation sails.js uses — purely to decide
     what to show; the real gate is the confirm_sail_participation RPC. */
  const myRequestConfirmState = (participation, sailDate, sailStartTime) => {
    const happened = new Date(`${sailDate}T${sailStartTime || "00:00"}`) <= new Date();
    if (!participation) return happened ? "ready" : "accepted";
    if (participation.crew_confirmed && participation.skipper_confirmed) return "both";
    if (participation.crew_confirmed) return "mine";
    return happened ? "ready" : "accepted";
  };

  (async () => {
    const session = window.CURRENT_AUTH ? await window.CURRENT_AUTH.getSession() : null;
    const paramSlug = new URLSearchParams(location.search).get("p");

    /* Supabase auth is the single source of truth for "who am I": an explicit
       ?p= always wins (viewing anyone's profile), otherwise a real session
       always resolves to MY real profile — never the demo persona — and only
       a genuinely logged-out visitor falls back to the fixed demo profile. */
    let slug;
    if (paramSlug) {
      slug = paramSlug;
    } else if (session) {
      const myProfile = await window.CURRENT_AUTH.getMyProfile();
      if (!myProfile) { location.href = "create-profile.html"; return; }
      slug = myProfile.slug;
    } else {
      slug = data.currentUser;
    }

    let p = await fetchRealProfile(slug);
    let isMine = false;
    let realOtherProfilesBySlug = {};

    if (p) {
      isMine = !!session && session.user.id === p.userId;
      /* Confirmed sailing history is public — fetched for ANY real profile,
         not just isMine, since anyone (including a logged-out visitor) may
         be viewing it. */
      const history = await fetchConfirmedHistory(p.userId);
      p.confirmedSails = history.confirmedSails;
      p.repeatConnections = history.repeatConnections;
      p.sailedWith = history.sailedWith;
      p.sailedWithMore = history.sailedWithMore;
      p.recent = history.recent;
      realOtherProfilesBySlug = history.otherProfilesBySlug;
    } else {
      p = data.profiles[slug];
      /* Your own profile is the one the crew-request loop (loop.js) can change:
         confirming a sail adds to your confirmed sails, recent sailing and sailed-with. */
      if (p && p.slug === data.currentUser && window.CURRENT_LOOP) p = window.CURRENT_LOOP.overlayMe(p);
      isMine = !!p && p.slug === data.currentUser;
    }

    if (!p) {
      root.innerHTML = `
        <div class="container"><div class="page-intro">
          <p class="eyebrow">Sailing profile</p>
          <h1 class="display-2">We could not find that profile.</h1>
          <a class="link-arrow" href="find-a-sail.html">Find a sail <span>→</span></a>
        </div></div>`;
      return;
    }

    /* My requests / My sails: only ever shown on your own REAL profile, while
       actually signed in as that account. p.userId only exists on a real
       Supabase profile — the demo persona never has one, even when isMine is
       true for a logged-out visitor — so this can never show on a demo
       profile or on someone else's real one. */
    const showDashboard = isMine && !!p.userId;
    let myRequests = [], mySails = [], myParticipationsBySail = new Map();
    if (showDashboard) {
      [myRequests, mySails, myParticipationsBySail] = await Promise.all([
        fetchMyRequests(p.userId), fetchMySails(p.userId), fetchMyParticipationsBySail(p.userId),
      ]);
    }

  const first = p.name.split(" ")[0];
  /* A confirmed connection's "other person" is a real profile (resolved
     above, keyed by slug), not necessarily one of data.js's sample sailors —
     check that first, falling back to the demo roster for demo profiles. */
  const person = (s) => realOtherProfilesBySlug[s] || data.profiles[s];
  const profileHref = (s) => `profile.html?p=${esc(s)}`;
  const src = {
    verified: `<span class="src src--verified">${verifiedTick("Verified")}Verified</span>`,
    provided: `<span class="src">Provided by ${esc(first)}</span>`,
    community: `<span class="src src--community">Community-backed</span>`,
  };
  const head = (title, tag) => `<div class="pf-head"><h2>${esc(title)}</h2>${tag}</div>`;
  const times = (n) => (n === 1 ? "once" : `${n} times`);
  const hasHistory = p.sailedWith.length > 0 || p.feedback.length > 0 || p.recent.length > 0;

  document.title = `${p.name} — Sailing profile — CURRENT`;

  root.innerHTML = `
    <!-- WHO IS THIS, AND WHAT KIND OF SAILOR? -->
    <section class="pf-intro" aria-labelledby="pf-name">
      <div class="container pf-intro__grid">
        <figure class="pf-photo">
          <div class="photo__frame" style="--ph:#b9c7cf;--pos:50% 35%">
            <div class="photo__media">
              <span class="pf-ini" aria-hidden="true">${esc(p.name.split(" ").map((w) => w[0]).join(""))}</span>
              ${p.heroPhoto ? `<img src="${esc(p.heroPhoto)}" alt="${esc(p.name)} sailing" decoding="async" onerror="this.hidden=true">` : ""}
            </div>
          </div>
        </figure>

        <div class="pf-id">
          <h1 class="pf-name" id="pf-name">${esc(p.name)}${p.verification.identity ? verifiedTick("Identity verified") : ""}</h1>
          <p class="pf-area">${esc(p.sailingArea)}</p>
          <p class="pf-types">${p.types.map(esc).join(" · ")}</p>
          <p class="pf-bio">${esc(p.bio)}</p>

          <dl class="pf-facts">
            <div><dt>Sailing since</dt><dd>${p.sailingSince}</dd></div>
            <div><dt>Roles</dt><dd>${p.roles.map((r) => esc(r.name)).join(" · ")}</dd></div>
            <div class="num"><dd>${p.confirmedSails}</dd><dt>confirmed sails</dt></div>
            <div class="num"><dd>${p.repeatConnections}</dd><dt>repeat connections</dt></div>
          </dl>

          <div class="pf-actions">
            <button class="btn btn--ghost" type="button" data-share>Share profile</button>
            ${isMine ? `<a class="btn btn--ghost" href="create-profile.html">Edit profile</a>` : ""}
          </div>
        </div>
      </div>
    </section>

    <dialog class="modal" aria-labelledby="share-title">
      <div class="modal__panel">
        <p class="label">Share profile</p>
        <h2 class="modal__title" id="share-title">Share ${esc(p.name.split(" ")[0])}’s profile</h2>
        <p class="modal__lede">Send this link anywhere sailors look for crew — a text, a club board, a crew list.</p>
        <p class="share-url">current.sailing/${esc(p.slug)}</p>
        <div class="modal__actions">
          <button class="btn btn--ghost" type="button" data-share-close>Close</button>
          <button class="btn" type="button" data-share-copy>Copy profile link</button>
        </div>
        <p class="small" role="status" aria-live="polite" data-share-status></p>
      </div>
    </dialog>

    <!-- WHAT KIND OF SAILOR? CAN I TRUST THE CONTEXT? -->
    <section class="pf-section" aria-label="Experience and credentials">
      <div class="container pf-two">
        <div class="pf-col">
          ${head("Experience", src.provided)}
          <h3 class="pf-sub">Boats sailed</h3>
          <ul class="pf-list">
            ${p.boats.map((b) => `<li><span>${esc(b.name)}</span><span class="pf-muted">${b.sails != null ? `${b.sails} sails` : esc(b.experience)}</span></li>`).join("")}
          </ul>
          <h3 class="pf-sub">Roles</h3>
          <ul class="pf-list pf-roles">
            ${p.roles.map((r) => `<li><strong>${esc(r.name)}</strong><span class="pf-muted">${esc(r.note)}</span></li>`).join("")}
          </ul>
        </div>

        <div class="pf-col pf-col--rule">
          ${head("Credentials", "")}
          <div class="pf-identity">
            ${p.verification.identity ? verifiedTick("Identity verified") : `<span class="verified verified--off" aria-hidden="true"></span>`}
            <div>
              <p class="pf-identity__title${p.verification.identity ? "" : " pf-identity__title--off"}">${p.verification.identity ? "Identity verified" : "Not verified yet"}</p>
              <p class="pf-muted pf-identity__note">Concept: a third-party identity check, such as ID.me. CURRENT does not store ID documents.</p>
            </div>
            ${p.verification.identity ? src.verified : ""}
          </div>
          <div class="pf-creds">
            ${p.credentials.map((c) => `
              <div class="pf-cred">
                <div>
                  <p class="pf-cred__issuer">${esc(c.issuer)}</p>
                  <p>${esc(c.name)}</p>
                  <p class="pf-muted">${c.number ? `Credential no. ${esc(c.number)} · ` : c.detail ? `${esc(c.detail)} · ` : ""}${c.year}</p>
                </div>
                <span class="src">Provided by ${esc(first)}</span>
              </div>`).join("")}
          </div>
        </div>
      </div>
    </section>

    ${hasHistory ? `
    ${!p.sailedWith.length ? "" : `
    <!-- WHO HAVE THEY ACTUALLY SAILED WITH? -->
    <section class="pf-section" aria-labelledby="pf-with">
      <div class="container">
        <div class="pf-head">
          <div>
            <h2 id="pf-with">Sailed with</h2>
            <p class="pf-muted pf-head__sub">People ${esc(first)} has sailed with on confirmed sails.</p>
          </div>
          ${src.community}
        </div>
        <ul class="pf-mates">
          ${p.sailedWith.map((w) => {
            const o = person(w.slug);
            return `<li><a class="pf-mate" href="${profileHref(o.slug)}">${avatar(o, "avatar--pf")}<span class="pf-mate__name">${esc(o.name)}</span><span class="pf-muted">${w.sails} sails</span></a></li>`;
          }).join("")}
          ${p.sailedWithMore ? `<li><span class="pf-mate pf-mate--more"><span class="pf-more">+${p.sailedWithMore}</span><span class="pf-mate__name">and ${p.sailedWithMore} more</span></span></li>` : ""}
        </ul>
      </div>
    </section>`}

    ${!p.feedback.length ? "" : `
    <!-- WHAT WAS IT LIKE TO SAIL WITH THEM? -->
    <section class="pf-section" aria-labelledby="pf-fb">
      <div class="container">
        <div class="pf-head"><h2 id="pf-fb">Sailing feedback</h2>${src.community}</div>
        <div class="pf-feedback">
          ${p.feedback.map((f) => {
            const o = person(f.from);
            const n = data.together(p.slug, o.slug) + (isMine && window.CURRENT_LOOP ? window.CURRENT_LOOP.extraTogether(o.slug) : 0);
            return `
              <article class="fb">
                ${avatar(o, "avatar--fb")}
                <div>
                  <p class="fb__who"><a href="${profileHref(o.slug)}">${esc(o.name)}</a></p>
                  <p class="fb__ctx">${esc(f.sail)} · ${esc(f.boat)}</p>
                  <p class="fb__quote">“${esc(f.quote)}”</p>
                  <p class="fb__foot">
                    <span>Sailed together ${times(n)}</span>
                    <span class="fb__again">${verifiedTick("Would sail together again")}Would sail together again</span>
                  </p>
                </div>
              </article>`;
          }).join("")}
        </div>
      </div>
    </section>`}

    <!-- WHAT HAVE THEY DONE RECENTLY? -->
    <section class="pf-section${showDashboard ? "" : " pf-section--last"}" aria-labelledby="pf-recent">
      <div class="container">
        <div class="pf-head"><h2 id="pf-recent">Recent sailing</h2>${src.community}</div>
        <ul class="pf-recent">
          ${p.recent.slice(0, 4).map((r) => `
            <li>
              <span class="pf-recent__date">${esc(r.date)}</span>
              <strong>${esc(r.title)}</strong>
              <span class="pf-recent__meta"><span>${esc(r.boat)}</span><span>${esc(r.place)}</span>${
                r.other ? `<span class="pf-muted">with ${esc(person(r.other)?.name || "")}</span>` : r.role ? `<span class="pf-muted">${esc(r.role)}</span>` : ""
              }</span>
            </li>`).join("")}
        </ul>
      </div>
    </section>` : `
    <!-- A brand-new profile has no CURRENT-generated history yet: no fake activity. -->
    <section class="pf-section${showDashboard ? "" : " pf-section--last"}" aria-labelledby="pf-recent">
      <div class="container">
        <div class="pf-head"><h2 id="pf-recent">Sailing history</h2>${src.community}</div>
        <div class="pf-empty">
          ${isMine
            ? `<p>Your CURRENT history starts when you sail with people through CURRENT.</p>
               <p class="pf-muted">After a sail, both sailors can confirm that you sailed together.</p>`
            : `<p>${esc(first)}’s CURRENT history starts when ${esc(first)} sails with people through CURRENT.</p>
               <p class="pf-muted">After a sail, both sailors can confirm that they sailed together.</p>`}
        </div>
      </div>
    </section>`}

    ${!showDashboard ? "" : `
    <!-- MY REQUESTS: every real crew request I've made, whatever its status. -->
    <section class="pf-section" aria-labelledby="pf-my-requests">
      <div class="container">
        <div class="pf-head"><h2 id="pf-my-requests">My requests</h2></div>
        ${myRequests.length ? `
          <div class="pf-creds">
            ${myRequests.map((r) => {
              const badge = (() => {
                if (r.status !== "accepted") return `<span class="src">${esc(REQUEST_STATUS_LABEL[r.status])}</span>`;
                const state = myRequestConfirmState(myParticipationsBySail.get(r.sails.id), r.sails.sail_date, r.sails.start_time);
                if (state === "ready") return `<a class="src src--community" href="sail.html?id=${esc(r.sails.id)}">Confirm sail</a>`;
                if (state === "mine") return `<span class="src">Waiting for confirmation</span>`;
                if (state === "both") return `<span class="src src--community">Confirmed sail ✓</span>`;
                return `<span class="src src--community">Accepted</span>`;
              })();
              return `
              <div class="pf-cred">
                <div>
                  <p class="pf-cred__issuer"><a href="sail.html?id=${esc(r.sails.id)}">${esc(r.sails.title)}</a></p>
                  <p class="pf-muted">${esc(fmtShortDate(r.sails.sail_date))} · ${esc(r.sails.location)}${r.sails.status === "closed" ? " · Closed" : ""}</p>
                </div>
                ${badge}
              </div>`;
            }).join("")}
          </div>` : `
          <div class="pf-empty">
            <p>You haven't requested to crew on any sails yet.</p>
            <p class="pf-muted"><a class="link-arrow" href="find-a-sail.html">Find a sail <span aria-hidden="true">→</span></a></p>
          </div>`}
      </div>
    </section>

    <!-- MY SAILS: every real sail I skipper. -->
    <section class="pf-section pf-section--last" aria-labelledby="pf-my-sails">
      <div class="container">
        <div class="pf-head"><h2 id="pf-my-sails">My sails</h2></div>
        ${mySails.length ? `
          <div class="pf-creds">
            ${mySails.map((s) => `
              <div class="pf-cred">
                <div>
                  <p class="pf-cred__issuer"><a href="sail.html?id=${esc(s.id)}">${esc(s.title)}</a></p>
                  <p class="pf-muted">${esc(fmtShortDate(s.sail_date))} · ${esc(s.location)}${s.sail_requests.length ? ` · ${s.sail_requests.length} crew ${s.sail_requests.length === 1 ? "request" : "requests"}` : ""}</p>
                </div>
                <div class="pf-cred__actions">
                  <span class="src${s.status === "open" ? " src--community" : ""}">${s.status === "open" ? "Open" : "Closed"}</span>
                  <a href="sail.html?id=${esc(s.id)}">View</a>
                  <a href="post-sail.html?id=${esc(s.id)}">Edit</a>
                </div>
              </div>`).join("")}
          </div>` : `
          <div class="pf-empty">
            <p>You haven't posted a sail yet.</p>
            <p class="pf-muted"><a class="link-arrow" href="post-sail.html">Post a sail <span aria-hidden="true">→</span></a></p>
          </div>`}
      </div>
    </section>`}`;

  /* Share profile: a conceptual public link, since the prototype has no real hosting for it. */
  const shareModal = root.querySelector(".modal");
  const shareStatus = shareModal.querySelector("[data-share-status]");
  root.querySelector("[data-share]").addEventListener("click", () => {
    shareStatus.textContent = "";
    shareModal.showModal();
  });
  shareModal.querySelector("[data-share-close]").addEventListener("click", () => shareModal.close());
  shareModal.addEventListener("click", (e) => { if (e.target === shareModal) shareModal.close(); });
  shareModal.querySelector("[data-share-copy]").addEventListener("click", async () => {
    const url = shareModal.querySelector(".share-url").textContent;
    try { await navigator.clipboard.writeText(url); } catch (e) { /* prototype link only; show the copied state regardless */ }
    shareStatus.textContent = "Profile link copied ✓";
  });
  })();
})();
